import os
import boto3
from botocore.exceptions import ClientError

s3_client = boto3.client('s3')
S3_BUCKET = os.getenv('S3_BUCKET', 'BioDockify-jobs-use1-1763775915')

def generate_vina_config(job_id: str, grid_params: dict = None):
    """
    Generate AutoDock Vina config file and store in S3
    
    Args:
        job_id: Job ID
        grid_params: Dict with grid_center_x/y/z and grid_size_x/y/z
                    If None, uses default values
    
    Returns:
        S3 key where config was stored
    """
    # Default grid parameters (center of box, reasonable size)
    params = grid_params or {}
    center_x = params.get('grid_center_x', 0.0)
    center_y = params.get('grid_center_y', 0.0)
    center_z = params.get('grid_center_z', 0.0)
    size_x = params.get('grid_size_x', 20)
    size_y = params.get('grid_size_y', 20)
    size_z = params.get('grid_size_z', 20)
    exhaustiveness = params.get('exhaustiveness', 64) # Increased for max precision
    num_modes = params.get('num_modes', 20)
    energy_range = params.get('energy_range', 5)
    
    # Generate config content
    config_content = f"""# AutoDock Vina Configuration File
# Generated by BioDockify
# Job ID: {job_id}

# Input files
receptor = receptor.pdbqt
ligand = ligand.pdbqt

# Grid box configuration
center_x = {center_x}
center_y = {center_y}
center_z = {center_z}

size_x = {size_x}
size_y = {size_y}
size_z = {size_z}

# Docking parameters
exhaustiveness = {exhaustiveness}
num_modes = {num_modes}
energy_range = {energy_range}

# Output
out = output.pdbqt
"""
    
    # Store in S3
    config_key = f"jobs/{job_id}/config.txt"
    
    try:
        s3_client.put_object(
            Bucket=S3_BUCKET,
            Key=config_key,
            Body=config_content.encode('utf-8'),
            ContentType='text/plain'
        )
        
        return config_key
    
    except ClientError as e:
        print(f"Error storing config file: {e}")
        raise


def get_presigned_download_url(s3_key: str, expiration=3600):
    """
    Generate presigned URL for downloading from S3
    
    Args:
        s3_key: S3 object key
        expiration: URL expiration in seconds (default 1 hour)
    
    Returns:
        Presigned URL string
    """
    try:
        url = s3_client.generate_presigned_url(
            'get_object',
            Params={'Bucket': S3_BUCKET, 'Key': s3_key},
            ExpiresIn=expiration
        )
        return url
    except ClientError as e:
        print(f"Error generating presigned URL: {e}")
        return None
