export default function TermsPage() {
    return (
        <div className="min-h-screen bg-slate-50 pt-32 pb-20">
            <div className="container mx-auto px-4">
                <div className="max-w-3xl mx-auto bg-white rounded-2xl p-8 md:p-12 shadow-sm border border-slate-200">
                    <h1 className="text-4xl font-bold text-slate-900 mb-8 tracking-tight">Terms of Service</h1>
                    <div className="prose prose-lg max-w-none text-slate-600">
                        <p className="text-slate-500 mb-8 text-sm">Last updated: November 23, 2025</p>

                        <h3 className="text-2xl font-bold text-slate-900 mt-10 mb-4">1. The "Zero-Cost" Mission</h3>
                        <p className="mb-6 leading-relaxed">
                            BioDockify is a community-driven initiative to democratize drug discovery. Use of the "7-Phase Pipeline" (Docking, MD, Analysis, etc.) is free of charge for academic and non-profit research, subject to our Fair Use Policy.
                        </p>

                        <h3 className="text-2xl font-bold text-slate-900 mt-10 mb-4">2. Fair Use Policy</h3>
                        <p className="mb-6 leading-relaxed">
                            To maintain free access for all users, we enforce the following limits:
                        </p>
                        <ul className="list-disc pl-6 mb-6 space-y-2">
                            <li><strong>Resource Usage:</strong> Please do not submit excessive concurrent jobs that could degrade service for others.</li>
                            <li><strong>Automation:</strong> Unauthorized scraping or bot-driven submission of jobs is prohibited.</li>
                        </ul>

                        <h3 className="text-2xl font-bold text-slate-900 mt-10 mb-4">3. Intellectual Property</h3>
                        <p className="mb-6 leading-relaxed">
                            <strong>Your Research is Yours.</strong> You retain full ownership of:
                        </p>
                        <ul className="list-disc pl-6 mb-6 space-y-2">
                            <li>All input data (protein structures, ligands) you upload.</li>
                            <li>All results generated by the pipeline, including docking poses, MD trajectories, ADMET reports, and ranking lists.</li>
                        </ul>
                        <p className="mb-6 leading-relaxed">
                            BioDockify claims no rights to any potential discoveries or patents resulting from the use of our platform.
                        </p>

                        <h3 className="text-2xl font-bold text-slate-900 mt-10 mb-4">4. Scientific Disclaimer</h3>
                        <p className="mb-6 leading-relaxed">
                            BioDockify is a computational research tool. Results from Virtual Screening, MD Simulations, and ADMET predictions are theoretical models and <strong>must be experimentally validated</strong> before clinical application. We are not liable for any research outcomes or decisions made based on these simulations.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    )
}
